### ISSUE TITLE
Add .env for SECRET in authentication

### ISSUE THREAD

**Issue by HelloEdit** [feathersjs/cli#111]
Hello,

When authentication is set up via  feathers CLI, the secret is exposed in the file `default.json`. People who are used to working with authentication will not have any trouble creating a `.env` file, but I think it would be nicer and more secure to have a default `.env` containing the automatically generated secret.
Obviously this implies some change, such as switching from `default.json` to `default.js` in config and installing dotenv.

Tell me what you think !

Thank,

**Comment by daffl** [comment]
You can already change the authentication secret value to an environment variable name in the configuration. I'd prefer the generated application to be able to run without installing external dependencies other than the database you choose especially since I don't think `.env` would work as easily on Windows.

**Comment by HelloEdit** [comment]
In this case, why not update the examples to mount how to further secure authentication ?

**Comment by HelloEdit** [comment]
@daffl I think this is a really important thing to do !

And `.env` work like a charm on Windows 😄

**Comment by daffl** [comment]
I'd be happy to revisit this in a pull request but don't plan on tackling this myself.

**Comment by HelloEdit** [comment]
If you confirm to me that the best thing to do is to pass token by a .env file with dotenv, I can try to deal with PR

**Comment by HelloEdit** [comment]
I didn't know anything about it. The token must not be displayed in the same file as other configurations. But the problem is solved with your solution! Thank you

**Comment by spidgorny** [comment]
For those who want to keep using .env (industry standard): adding these two lines in the beginning of src/index.ts works as expected.
```
import dotenv from 'dotenv';
dotenv.config();
```

Test with
```
console.log(app.get('authentication').oauth.twitter);
```

**Comment by vasudeveloper001** [comment]
> For those who want to keep using .env (industry standard): adding these two lines in the beginning of src/index.ts works as expected.
> 
> ```
> import dotenv from 'dotenv';
> dotenv.config();
> ```
> 
> Test with
> 
> ```
> console.log(app.get('authentication').oauth.twitter);
> ```

Thanks. This solved my problem. Don't understand the design decision to delegate such simple task to *.json file and reading the documentation was still quite confusing.
