### ISSUE TITLE
The `useMongoClient` option is no longer necessary in mongoose 5.x

### ISSUE THREAD

**Issue by dobeerman** [feathersjs/cli#136]
Subj. 
Please remove it from `src/mongoose.js`

**Comment by daffl** [comment]
You can submit a pull request by editing the file in the browser accordingly at https://github.com/feathersjs/generator-feathers/edit/master/generators/connection/templates/mongoose.js

**Comment by daffl** [comment]
Closed via https://github.com/feathersjs/generator-feathers/pull/330, will be release shortly. Thank you for the pull request!

**Comment by erkanokman** [comment]
//Connect to mongoose (
mongoose.connect(db.mongoURI, {

	 useNewUrlParser: true    //add it
	//useMongoClient: true //old

})
.then(() => console.log('Veri baglantisi saglandi...'))
.catch(err =>console.log(err));

**Comment by SumithEkanayake** [comment]
This warning occurs beacuase the `useMongoClient `option is no longer supports to mongoose new versions (>5.x).

solution is remove 
        `useMongoClient: true //remove this code`
    

and replace it with
`useNewUrlParser: true //remove this code`

**Example**

    mongoose.connect('<<your uri>>', {
    // useMongoClient: true
    useNewUrlParser: true
});
