### ISSUE TITLE
Feature: List updated/new files

### ISSUE THREAD

**Issue by rafamel** [feathersjs/cli#143]
This is just a feature request for consideration. The cli is really handy but I personally find myself going around checking the bits changed by the generator and fitting them to my setup. It would be great to have a verbose mode that listed all new and updated files.

Thanks for reading,
Rafa.

**Comment by daffl** [comment]
I'm not sure I follow. Isn't that what it currently does?

<img width="489" alt="screen shot 2018-02-23 at 12 57 13 pm" src="https://user-images.githubusercontent.com/338316/36616572-195ab1c6-1899-11e8-939e-88e98bfb09b0.png">

**Comment by rafamel** [comment]
Thank you for the answer, David. You're absolutely right, it was my mistake; I should have looked into it further. I was running it on a pseudo terminal and some messages were getting  swallowed up all over - not just with the feathers cli.

Sorry that I took your time with this; please do close the issue.
Rafa.

**Comment by daffl** [comment]
All good, suggestions are always welcome.
