### ISSUE TITLE
Generate Service stops responding at "What is the database connection string"

### ISSUE THREAD

**Issue by linck5** [feathersjs/cli#144]
### Steps to reproduce

When generating a service, when I'm prompted with "What is the database connection string", the console stops responding to any commands. The text cursor is still blinking, the system is still responding, but there is nothing I can do other than close the console window. Ctrl+C doesn't work, I tried many combinations of keys but nothing I do causes any effect.

To reproduce:
1. on windows, open cmd.exe
2. cd to an empty folder
3. `feathers generate app`, type any name, default for all options
4. `feathers generate service`, type any name, default for all options

I can generate other service, for instance using "A custom service" as the first option, without a problem.

Screenshot:
[https://i.imgur.com/0qAm2JP.png](url)

### Expected behavior
Be able to type a string when asked for connection string, and press return to advance

### Actual behavior
I can't type anything, return key does nothing

### System configuration

**Module versions** (especially the part that's not working):
feathers 3.6.1

**NodeJS version**:
8.1.0

**Operating System**:
win10 x64

PS: I realize that this is probably an issue on my end, but I failed to find anyone with a similar issue, perhaps I didn't use the correct keywords on the google search. I'm hoping I can get some guidance here, so I appreciate any little help.

**Comment by linck5** [comment]
I have solved this issue by upgrading to node v9.7.0

**Comment by daffl** [comment]
I think we can close this then. Thanks for the update!
