### ISSUE TITLE
.sequelizerc could be evaluated before generating a service based on Sequelize

### ISSUE THREAD

**Issue by schettino** [feathersjs/cli#146]
After changing the default paths in .sequelizerc, generating a service still uses the same path configuration. For example, a top-level _models_ folder would be created again even if you have changed it in the .sequelizerc.

**Comment by daffl** [comment]
I remember there was some discussion of using the Sequelize CLI to generate models which would be nice. The probably easiest way for now would be to try and read `.sequelizerc` and get the model folder. How do those files look like?

**Comment by daffl** [comment]
This issue was moved to feathersjs/feathers#955
