### ISSUE TITLE
couchDB not visible in feathersJs when creating service

### ISSUE THREAD

**Issue by Dmedip** [feathersjs/cli#162]
Hello
I am trying ti use couchDB for feathersJs,when I am trying to create service I could not see the option couchdb. 
I did npm install cradle feathers-couchdb --save
What are the steps to follow.Please help
Thanks
PS C:\pcs-sample\node-feathers> feathers generate service
  What kind of service is it? (Use arrow keys)
  A custom service
  In Memory
  NeDB
  MongoDB
  Mongoose
  Sequelize
  KnexJS
(Move up and down to reveal more choices)

**Comment by daffl** [comment]
The CouchDB adapter is not supported by the generator, it needs to be included manually.

**Comment by daffl** [comment]
If the CouchDB adapter supports all of the common query syntax and someone is interested in adding it to the generator that would be great, going to close this issue though.
