### ISSUE TITLE
The generated test command is not working in windows os

### ISSUE THREAD

**Issue by mohamed-seada-1994** [feathersjs/cli#172]
### The Problem
The generated test command is not working in windows os
`npm run eslint && NODE_ENV= npm run jest`

### Expected behavior
Test is Running
### Actual behavior
`'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.`

### System configuration
**NodeJS version**:
10.15.0
**Operating System**:
win 10

#### Idea No.1
We can install `win-node-env` module as optional dependencies
` npm install --save-optional win-node-env `
but we still has a problem of parsing `NODE_ENV=` without any specific value
so test commend should be
`npm run eslint && NODE_ENV=default npm run jest`
but we will get an error caused be node-config
` WARNING: NODE_ENV value of 'default' is ambiguous. `

#### Idea No.2
We just can add test.json file with empty json object in config and remove `NODE_ENV` from the command
`npm run eslint &&  npm run jest`

**Comment by Mattchewone** [comment]
Perhaps it should leverage - https://www.npmjs.com/package/cross-env

**Comment by mohamed-seada-1994** [comment]
@Mattchewone It works fine with me `npm run eslint && cross-env NODE_ENV= npm run jest`

**Comment by eddyystop** [comment]
cli+ uses cross-env . Its the easiest way we found to support inline environment variables.

**Comment by s-oram** [comment]
It fails for me on a newly created project. 

```
$ npm test

> npm run eslint && NODE_ENV= npm run jest

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
```
