### ISSUE TITLE
EINVAL Error on npm install @feathers/cli

### ISSUE THREAD

**Issue by xOrMalware** [feathersjs/cli#181]
This maybe a Node/NPM issue, however, I am here first to rule out a feathers issue, as it is the cli module I am trying to install. I was wondering if this was a dependency issue?
[2019-06-23T17_08_33_072Z-debug.log](https://github.com/feathersjs/cli/files/3318340/2019-06-23T17_08_33_072Z-debug.log)

My configuration is as follows
Node Version: v10.15.3
OS: Windows10
Command run: npm install @feathersjs/cli

The attached log file shows an EINVAL error. This project was working fine, but I have not run the project in a few days, as I was do something else. The only thing of difference is moving my source repositories from a local disk, to an external drive.

However, any pointers would be greatly received.

**Comment by xOrMalware** [comment]
Right so I have 'fixed' the above issue. Running

npm install -g @feathersjs/cli

Got what I needed to work. However, when I run

feathers generate connection

selecting mongodb and and native mongo drivers. I get a similar error message in the log file EINVAL: invalid argument.

I have since I posted the original issue, upgraded my node installation. So I am now on
Node: 12.4.0
NPM: 6.9.0

Its probably something obvious, but better minds than I might see what I am doing wrong.

[2019-06-25T13_12_40_683Z-debug.log](https://github.com/feathersjs/cli/files/3325419/2019-06-25T13_12_40_683Z-debug.log)

**Comment by ucokfm** [comment]
Can you try by deleting "node_modules" folder, and then run "npm install" again?
My googling result said this is maybe related to different filesystem of local disk (NTFS) and external disk (FAT32).

**Comment by xOrMalware** [comment]
So I recreated the external encrypted drive as an NTFS partition type, and re-ran NPM install and then feathers generate connection, and as your elluded to, it worked fine.

All is now good, in my JS universe, at least now. Many thanks for your help.
