### ISSUE TITLE
Missing uws dependency in engine.io server.js feathers dependency

### ISSUE THREAD

**Issue by KnowledgeGarden** [feathersjs/cli#182]
## Background
Installed a feathers api inside a vue client.
Feathers boots
Vue will not compile. It insists that a dependency "uws" is missing inside the api (feathers) libraries.
On an older feathers cli, the dependency was there, but empty with a warning it was discontinued.
On the very latest feathers cli, it's just not there at all, even though the feathers dependency engine.io still needs it.

### Steps to reproduce
Create a new feathers api in <project>/api with realtime and rest
Then create a vue client in <project> and add an api.js which uses these imports
import feathers from '@feathersjs/feathers'
import socketio from '@feathersjs/socketio-client'
import auth from '@feathersjs/authentication-client'
import io from 'socket.io-client'
Then boot them.

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))
googlefoo does not lead me here It leads me to a variety of places where this issue is talked about, mostly in vue contexts, not feathers cli contexts. It's possible I missed something and it's already solved. I'd like that to be the case, if only this can be solved easily.

- [ ] Tell us what broke. The more detailed the better.
Consider this console report when booting the vue client reporting a compiler failure

This dependency was not found:
* uws in ./api/node_modules/engine.io/lib/server.js
To install it, you can run: npm install --save uws

googlefoo suggests adding uws to the vue client package.json
(to me, that seems nonsensical because it's a feathers dependency, not a vue dependency)

Observation, and this is why I am here: I built the feathers twice, second time after I updated to the latest cli hoping this would go away (it didn't); it is still calling for an **engine.io** which insists on loading a version of uws which, according to the engine.io package.json is "uws": "~9.14.0"
But, there is no uws package either in the engine.io node_modules or in the outer api/node_modules.

With the older cli version, there was, in fact, a uws in api/node_modules but it was just a package.json with a lot of messages, and a readme that says the product was discontinued.

### Expected behavior
What should happen is that Vue console will tell me it's up and running on port 8080

### Actual behavior
The console above said it all; compiler error. Backtracking from the vue api.js to the innards of the feathers platform, it could not make connections by way of engine.io to engine.io's call to import uws. It's just not there. Why the feathers compiler didn't find that is a mystery to me, but then, this is relatively new to me.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
Here's what's in my feathers app
   "@feathersjs/authentication": "^2.1.16",
    "@feathersjs/authentication-jwt": "^2.0.10",
    "@feathersjs/authentication-local": "^1.2.9",
    "@feathersjs/configuration": "^2.0.6",
    "@feathersjs/errors": "^3.3.6",
    "@feathersjs/express": "^1.3.1",
    "@feathersjs/feathers": "^3.3.1",
    "@feathersjs/socketio": "^3.2.9",

In theory, that's what I got when I did a fresh npm i @feathers/cli before this
**NodeJS version**:
12.4.0
**Operating System**:
MacOs mojave
**Browser Version**:
we're not even to the browser yet
**Module Loader**:
npm 6.9.0

**Comment by daffl** [comment]
Since the Feathers CLI does nothing frontend related I'd recommend separating the server and frontend code.

The most likely reason for this error is that your app is pulling in `@feathersjs/socketio` instead of `@feathersjs/socketio-client` somewhere.

**Comment by KnowledgeGarden** [comment]
Indeed! They are separated.
App.js, made by vue cli does bring in @feathersjs/socketio. But, the codebase that is running on, made with older feathers cli, is online and running fine. Very confusing.

**Comment by daffl** [comment]
It should not. Server side code should not be built for the client, only [Feathers client](https://docs.feathersjs.com/api/client.html) side modules.
