### ISSUE TITLE
4.0.0pre4 cli initial an project with mongoose with an error

### ISSUE THREAD

**Issue by hustlemickey** [feathersjs/cli#183]
### Steps to reproduce

with 4.0.0 cli,    feathers g app ,   select typescript, then select mongoose as db,  when project init finish,  start with "npm start"
### Expected behavior
project start without error

### Actual behavior
error with Invalid module name in augmentation. Module 'mongodb-core'
### System configuration

config are all default

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
Should be fixed in `@feathersjs/cli@4.0.0-pre.5`
