### ISSUE TITLE
Type error test/authentication.test.ts

### ISSUE THREAD

**Issue by bartduisters** [feathersjs/cli#187]
### Steps to reproduce

Generate a new application and choose TypeScript as a language
```feathers generate app```

Open authentication.test.ts (in VSCode)

### Expected behavior
No type errors to be shown.

### Actual behavior
A type error is shown.
![image](https://user-images.githubusercontent.com/43420049/64186709-951e6680-ce6f-11e9-89cd-fcc991995e86.png)

Fix, add an empty object where TypeScript expects a 'params' object:
![image](https://user-images.githubusercontent.com/43420049/64186745-a6677300-ce6f-11e9-9f5f-3358761fa747.png)

I could not find where the code that gets generated lives.

**Comment by daffl** [comment]
It's interesting that the tests still seem to be passing. I had some improvements in the services typings anyway so this will be hopefully addressed at the same time.
