### ISSUE TITLE
MongoDB no longer offered in feather cli

### ISSUE THREAD

**Issue by p3nt4** [feathersjs/cli#193]
### Steps to reproduce

Im running the following command:
```
./node_modules/@feathersjs/cli/bin/feathers.js generate connection;
```

### Expected behavior
The last time I ran this command, the mongodb/mongoose option was offered.

### Actual behavior
The following options are offered:
```
  MySQL (MariaDB) 
❯ PostgreSQL 
  SQLite 
  SQL Server
```
My environment has not changed and the projects I created in the past still function with mongodb.

### System configuration

Linux 4.15.0-kali2-amd64 #1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU/Linux

npm: version 5.8.0

node: version v10.15.2

feathers_cli: version 4.2.1

**Comment by p3nt4** [comment]
It seems like this was caused by using a cli version 4 with feathers version 3.

**Comment by josx** [comment]
Error open about this in  feathersjs/generator-feathers#499
