### ISSUE TITLE
Error with version 4.4.0

### ISSUE THREAD

**Issue by Barbapapazes** [feathersjs/cli#231]
### Steps to reproduce

Try to generate a hook using v4.4.0 of Feathers/cli, with feathersjs 4.5.5

### Expected behavior

It should work

### Actual behavior

An error occured when using the 4.4.0 version but when restoring to 4.3.0 version, everything is working fine !

(first try is with 4.4.0, second is after restoring to 4.3.0)
![image](https://user-images.githubusercontent.com/45267552/87774811-598d5080-c825-11ea-9f6d-a1aecc044b37.png)

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): 4.4.0

**NodeJS version**: 12.14.1

**Operating System**: Windows 10.0.19041.329

**Browser Version**: /

**React Native Version**: /

**Module Loader**: /

**Comment by daffl** [comment]
I am not able to reproduce this. Can you please provide a sample repository where this would fail?
