### ISSUE TITLE
gen chat app issue

### ISSUE THREAD

**Issue by msimonc** [feathersjs/cli#235]
Used the cli to gen the chat server.  
Created code was missing the messages service code and folder; started but didn't run.

Workaround:  Cloned that app from github, no issues.

**Comment by daffl** [comment]
The CLI generates a Feathers application, not the chat application. You have to follow [the Feathers guide](https://docs.feathersjs.com/guides/) to [generate the services](https://docs.feathersjs.com/guides/basics/services.html) and add the chat application functionality.
