### ISSUE TITLE
Automated testing environment

### ISSUE THREAD

**Issue by DenJohX** [feathersjs/cli#27]
Often the code needs to be tested with access to the database or some other service, thus making neccesary to run the tests in a different environment.

Should the generator provide an ready to use automated testing environment for this?

For example with:
- A ready to use `testing.json` config, to run with `NODE_ENV=testing mocha`.
- A basic reset database script to run before testing
- Some example tests with database dummy-filling and testing

**Comment by daffl** [comment]
A test specific database environment is now documented in the [testing guide](https://docs.feathersjs.com/guides/chat/testing.html). We may include this in the generated code in the future but I think it is a good start.
