### ISSUE TITLE
[3.0] CLI is not respecting directory

### ISSUE THREAD

**Issue by ekryski** [feathersjs/cli#39]
I'll need to revisit this but I think the last time I ran the new CLI it did not put the files inside the newly created directory.

**Comment by MrPhilbert** [comment]
Same here. It puts my terminal (bash on windows or cmd) to the root directory of my computer.

**Comment by daquinons** [comment]
Same (macOS Sierra). It looks like is not only not respecting the directory but also the bash_profile, my account is named "local" after executing a cli command, the colors of my terminal are gone, etc.

**Comment by radmen** [comment]
Just downloaded `feathers-cli`. Tried to create my first app. Didn't go well. Generator created application in my root dir, although my CWD was different.

I've saw that `feathers` printed:
```
~/app # feathers generate app

Just found a `.yo-rc.json` in a parent directory.
Setting the project root at: /root
```

When I removed `.yo-rc.json` file `generate app` went as expected.

**Comment by ekryski** [comment]
@radmen thanks. That's actually a separate issue I think. It wouldn't be applicable in v3 because we're not using Yo in that version.

Not sure what we need to do to handle `.yo-rc.json` files. Maybe we just warn people, but it's not entirely a Feathers issue because this is something that was likely left around from another Yeoman generator or project and because v2 CLI is using Yo it picked it up.
